import "./globals.css";

export const metadata = {
  title: "Marvel Watchlist",
  description: "Generated by Ulas Demir",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="font-comic antialiased bg-comic-white"
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
