import "./globals.css";
import { LanguageProvider } from "@/context/LanguageContext";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Marvel Watchlist",
  description: "Generated by Ulas Demir",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="font-comic antialiased bg-comic-white"
        suppressHydrationWarning
      >
        <LanguageProvider>
          <Navbar />
          <main>{children}</main>
        </LanguageProvider>
      </body>
    </html>
  );
}
